/**
 * Shared utilities for consumer tag translators.
 *
 * Consumer tags (<create-draggable>, <create-droppable>, <create-sortable>)
 * all follow the same pattern:
 *
 *   1. Do standard custom tag translation (CustomTag.translate.exit).
 *   2. Get the child scope binding from tag.node.extra via symbol lookup.
 *   3. Import findDndManager from our runtime package.
 *   4. Import the child's $_dndManager input signal using the exact export
 *      name from the child's analyzed binding (not a constructed name).
 *   5. Add an EFFECT statement that:
 *        - calls findDndManager(scope) to walk the branch chain
 *        - calls $_dndManager(childScope, manager) to pass it to the child
 *
 * The effect fires AFTER child's onMount (FIFO queue: child effects queued
 * first during _create_x(childScope) in $setup, our _script queued after
 * by getSignalFn appending to signal.render). Verified from signals.ts:563.
 */

import { types as t } from '@marko/compiler';
import {
  importNamed,
  loadFileForTag,
} from '@marko/compiler/babel-utils';
import { addStatement } from '@marko/runtime-tags/translator/util/signals';
import { getSection } from '@marko/runtime-tags/translator/util/sections';
import {
  createScopeReadExpression,
} from '@marko/runtime-tags/translator/util/scope-read';
import { isOutputDOM } from '@marko/runtime-tags/translator/util/marko-config';
import { scopeIdentifier } from '@marko/runtime-tags/translator/visitors/program';
import CustomTag, {
  getTagRelativePath,
} from '@marko/runtime-tags/translator/visitors/tag/custom-tag';
import { getKnownFromPropTree } from '@marko/runtime-tags/translator/util/binding-prop-tree';

// The property name in the child template's Input interface for the hidden manager.
// Must match the _dndManager field in each consumer tag's Input interface.
const DND_MANAGER_INPUT_PROP = '_dndManager';

// The runtime package export path for findDndManager.
const FIND_MANAGER_MODULE = '@dnd-kit/marko/runtime/context';
const FIND_MANAGER_EXPORT = 'findDndManager';

/**
 * The Symbol description used by knownTagAnalyze to store the child scope
 * binding on tag.node.extra. Verified from known-tag.ts source:
 *   const kChildScopeBinding = Symbol("known tag scope binding");
 */
const CHILD_SCOPE_SYMBOL_DESC = 'known tag scope binding';

export function consumerEnter(tag: t.NodePath<t.MarkoTag>): void {
  // CustomTag.translate.enter is a no-op for DOM output.
  CustomTag.translate.enter(tag);
}

export function consumerExit(tag: t.NodePath<t.MarkoTag>): void {
  if (!isOutputDOM()) {
    CustomTag.translate.exit(tag);
    return;
  }

  const file = tag.hub.file;
  const tagSection = getSection(tag);
  const relativePath = getTagRelativePath(tag);

  // ── Step 1: Capture child scope binding BEFORE tag is removed ────────────
  //
  // knownTagAnalyze (called during the analyze phase) stores the child scope
  // binding on tag.node.extra under a private Symbol with description
  // "known tag scope binding". We retrieve it via Object.getOwnPropertySymbols.
  //
  // This MUST happen before CustomTag.translate.exit(tag) which calls tag.remove().
  const extraSymbols = Object.getOwnPropertySymbols(tag.node.extra ?? {});
  const childScopeSymbol = extraSymbols.find(
    (s) => s.description === CHILD_SCOPE_SYMBOL_DESC
  );

  if (!childScopeSymbol) {
    throw tag.buildCodeFrameError(
      '[dnd-kit/marko] Could not find child scope binding on tag.node.extra. ' +
      'This is an internal error — please report it.'
    );
  }

  const childScopeBinding = (tag.node.extra as any)[childScopeSymbol];

  // ── Step 2: Get the exact export name for the _dndManager input signal ────
  //
  // Export names are generated by generateUid(binding.name) during the
  // analyze phase of the child template. For _dndManager, this produces
  // "$_dndManager". We read it from the child's analyzed binding — NOT by
  // constructing it from the property name — because the UID counter is
  // context-dependent (though deterministic per-file).
  const childFile = loadFileForTag(tag);
  if (!childFile) {
    throw tag.buildCodeFrameError(
      '[dnd-kit/marko] Could not load child file for tag.'
    );
  }

  const childExtra = childFile.ast.program.extra;
  const childExports = (childExtra as any).domExports;
  const dndManagerPropTree = getKnownFromPropTree(
    childExports?.params,
    DND_MANAGER_INPUT_PROP
  );

  if (!dndManagerPropTree || dndManagerPropTree === true) {
    throw tag.buildCodeFrameError(
      `[dnd-kit/marko] Child tag is missing the \`${DND_MANAGER_INPUT_PROP}\` ` +
      'input property. Ensure the tag template declares it in its Input interface.'
    );
  }

  const managerExportName = (dndManagerPropTree as any).binding.export as string;

  // ── Step 3: Import the child's manager input signal ───────────────────────
  const managerInputFn = importNamed(
    file,
    relativePath,
    managerExportName,
    '_dnd_input_mgr'
  ) as t.Identifier;

  // ── Step 4: Import findDndManager from our runtime package ────────────────
  const findManagerFn = importNamed(
    file,
    FIND_MANAGER_MODULE,
    FIND_MANAGER_EXPORT,
    '_dnd_find_manager'
  ) as t.Identifier;

  // ── Step 5: Standard custom tag translation ───────────────────────────────
  // This handles: attribute input signals, tag var wiring, template/walks
  // injection, and tag.remove(). The child scope binding captured above
  // remains valid because addStatement uses the section's signal system.
  CustomTag.translate.exit(tag);

  // ── Step 6: Inject effect statement ──────────────────────────────────────
  //
  // TIMING: getSignalFn (signals.ts:563) pushes the _script call to
  // signal.render AFTER all existing render statements. Since
  // _create_x(childScope) is added to signal.render by CustomTag.translate.exit
  // (step 5), and our _script is pushed after, the FIFO queue ordering is:
  //   [child effects] → [our effect]
  //
  // By the time our effect fires:
  //   - $input phase has completed: manager IS on the branch ✓
  //   - We call findDndManager(scope) → walks branch chain → finds manager
  //   - We call $_dndManager(childScope, manager) → triggers child reactive update
  //   - Child's lifecycle onUpdate fires (rendering=1, synchronous cascade)
  //   - Entity is created and registered ✓
  const childScopeExpr = createScopeReadExpression(childScopeBinding, tagSection);

  const effectStatement = t.expressionStatement(
    t.callExpression(managerInputFn, [
      childScopeExpr,
      t.callExpression(findManagerFn, [scopeIdentifier]),
    ])
  );

  // undefined referencedBindings: runs once on mount (no reactive deps).
  // The _script is appended to signal.render by getSignalFn, appearing
  // in $setup AFTER _create_x(childScope). ✓
  addStatement('effect', tagSection, undefined, effectStatement);
}
