name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: ${{ matrix.channel }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write # Required for OIDC
      contents: write # Required for changesets/action@v1
      pull-requests: write # Required for changesets/action@v1
    strategy:
      max-parallel: 1
      matrix:
        channel:
          - current
          - beta
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          # https://github.com/atlassian/changesets/issues/550#issuecomment-811245508
          registry-url: 'https://registry.npmjs.org'

      # npm 11.5.1+ is required for OIDC trusted publishing to npm.
      - run: npm install -g npm@11

      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
      - run: bun install && bun run build

      - name: Create Release Pull Request or Publish to npm
        if: matrix.channel == 'current'
        uses: changesets/action@d94a5c301145045a0960133674e003b265942a22 # v1.8.0
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages on npm with @beta tag
        if: matrix.channel == 'beta'
        run: |
          npm run version-packages:beta
          npm run release:beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
